(cl:defpackage dynamic_biped-msg
  (:use )
  (:export
   "<ECJOINTMOTORDATA>"
   "ECJOINTMOTORDATA"
   "<QUATERNIONARRAY>"
   "QUATERNIONARRAY"
   "<HANDROTATION>"
   "HANDROTATION"
   "<HANDROTATIONEULAR>"
   "HANDROTATIONEULAR"
   "<ROBOTARMINFO>"
   "ROBOTARMINFO"
   "<ROBOTHANDPOSITION>"
   "ROBOTHANDPOSITION"
   "<ROBOTHEADMOTIONDATA>"
   "ROBOTHEADMOTIONDATA"
   "<ROBOTPHASE>"
   "ROBOTPHASE"
   "<ROBOTQVTAU>"
   "ROBOTQVTAU"
   "<ROBOTTORSOSTATE>"
   "ROBOTTORSOSTATE"
   "<WALKCOMMAND>"
   "WALKCOMMAND"
  ))

